name: gLEC
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jigsaw
  - jigsawpy
  - matplotlib
  - meshio 
  - methodtools 
  - mpi4py
  - numpy
  - rasterio
  - scipy
  - pip:
    - '--editable=.'
